version: '2'

services:
  nginx:
    image: linuxserver/nginx
    volumes:
        - /share/vdjbase/config/nginx:/config
        - /share/vdjbase/shared:/vdjbase
    ports:
       - 6000:80
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
  vdjbase:
    image: vdjbase
    container_name: vdjbase
    volumes:
        - /share/vdjbase/shared:/scratch
    restart: unless-stopped
		